---
- name: Install onnxruntime-gpu 
  ansible.builtin.pip:
    name:
      - onnxruntime
      - onnxruntime-gpu
    extra_args: --index-url=https://pypi.jetson-ai-lab.io/jp6/cu126
  become: true

- name: Install additional deps
  ansible.builtin.apt:
    pkg:
    - libasound-dev
    - portaudio19-dev
    - libportaudio2
    - ffmpeg
    - flac
  become: true

- name: Copy root application code
  copy:
    src: "{{ playbook_dir }}/.."
    dest: ~/

- name: Install global python dependencies
  ansible.builtin.pip:
    requirements: ~/pocket-infer-sw/python/requirements.txt
    virtualenv: ~/pocket-infer-sw/python/venv
    virtualenv_site_packages: yes
    
