---
- name: Collect serial-number
  shell: cat /proc/device-tree/serial-number
  register: serial

- name: Collect hostname
  command: python -c 'f=open("/proc/device-tree/serial-number");val=f.read();f.close();print("pocket-infer-"+hex(int(val.rstrip("\x00")))[-4:])'
  register: hostname 

- name: Set Hostname
  shell: "hostname {{ hostname.stdout }}"
  become: true

- name: Store hostname
  shell: "echo '{{ hostname.stdout }}' > /etc/hostname"
  become: true

- name: Disable GUI session
  shell: systemctl set-default multi-user
  become: true

# # Needed for seeedstudio carrier board:
# # The nvidia-l4t-bootloader cannot be updated on custom hardware
# # And it's a dependency for several other packages
# - name: Prepare for apt upgrade
#   shell: sudo apt-mark hold nvidia-l4t-bootloader nvidia-l4t-display-kernel nvidia-l4t-kernel nvidia-l4t-kernel-dtbs nvidia-l4t-kernel-headers nvidia-l4t-kernel-oot-headers nvidia-l4t-kernel-oot-modules
#   become: true

# May be needed for carrier board
- name: Ensure all Jetpack SDK components are installed
  shell: apt update && apt install -y nvidia-jetpack
  become: true

- name: Ensure Docker is installed
  ansible.builtin.shell:
    cmd: "curl https://get.docker.com | sh"
    creates: "/usr/bin/docker" # Skip if this file exists

- name: Set docker user
  shell: usermod -aG docker $USER
  become: true

- name: Copy cuda-keyring deb file
  copy:
    src: cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring_1.1-1_all.deb

- name: Install the cuda-keyring deb
  ansible.builtin.apt:
    deb: /tmp/cuda-keyring_1.1-1_all.deb
    state: present
  become: true

- name: Update and upgrade all apt packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
  become: true # Required for apt operations

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt # Specify 'apt' for Debian-based systems
  register: package_facts_result

- name: Install pytorch dependencies
  ansible.builtin.apt:
    pkg:
    - nvidia-jetpack
    - cusparselt-cuda-12
    - cudss
    - python3-pip
    - libopenblas-dev
    - libcusparselt-dev
    - cuda-cupti-12-6
  become: true

- name: Install project apt dependencies
  ansible.builtin.apt:
    pkg:
    - v4l-utils
    - htop
    - virtualenv
    - python3-pip
    - python3-setuptools
    - ffmpeg
  become: true

- name: Install global python dependencies
  ansible.builtin.pip:
    name:
      - jetson-stats==4.3.2
      - Jetson.GPIO==2.1.12
  become: true

# - name: Install pytorch
#   ansible.builtin.pip:
#     name:
#       - torch==2.8.0
#       - torchvision==0.23.0
#       - torchaudio==2.8.0
#     extra_args: --index-url=https://pypi.jetson-ai-lab.io/jp6/cu126
#   become: true
# 